### ISSUE TITLE
Colorize Tux

### ISSUE THREAD

**Issue by indiesquidge** [cldwalker/tux#9]
This is just something on the side and no problem with the functionality, but it would be nice to have a gem that would colorize Tux the way Pry can be colored.

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 12 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/tux#9). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by cldwalker** [comment]
Thanks for the feedback. I'm not looking to have tux pull in colorizing functionality by default. This can be done independently of tux. Since tux is based on [ripl](https://github.com/cldwalker/ripl), you can create [a ripl plugin](https://github.com/cldwalker/ripl#plugins) to colorize output as you'd like. You could look to gems like colorize and ripl-color_streams for inspiration.
